/**
 * The app's remote design system, as the panel edits it.
 * COPY_GROUPS is GENERATED from `Zennara App/constants/copy.ts` — regenerate
 * rather than hand-editing, so the two never drift.
 */
export type ColorToken = { key: string; label: string; hint: string; default: string };

export const COLOR_TOKENS: ColorToken[] = [
  { key: "primary", label: "Primary (brand green)", hint: "Buttons, active icons, links — the app's main colour. Pressed/secondary shades follow it automatically.", default: "#032F22" },
  { key: "gold", label: "Accent (champagne gold)", hint: "Membership, premium highlights and badges.", default: "#E0C391" },
  { key: "background", label: "Screen background", hint: "The ground behind every screen.", default: "#FFFFFF" },
  { key: "surface", label: "Cards & inputs", hint: "Cards, sheets, inputs and navigation.", default: "#FFFFFF" },
  { key: "sage", label: "Soft panels (sage)", hint: "Icon chips, selected states, subtle panels.", default: "#EFF3EE" },
  { key: "text.primary", label: "Headings & primary text", hint: "Titles and main copy.", default: "#111714" },
  { key: "text.secondary", label: "Body text", hint: "Descriptions and supporting copy.", default: "#4F5853" },
  { key: "text.muted", label: "Muted text", hint: "Metadata, captions, inactive labels.", default: "#7A827E" },
  { key: "border", label: "Borders", hint: "Card and input outlines.", default: "#E8E3DA" },
  { key: "success", label: "Success", hint: "Confirmations and positive states.", default: "#267A50" },
  { key: "warning", label: "Warning", hint: "Cautions and pending states.", default: "#9A5B13" },
  { key: "error", label: "Error", hint: "Failures and destructive actions.", default: "#B42318" },
];

/** Component-level roles. These are intentionally separate from the raw
 * palette so a button, input, header or tab bar can change independently. */
export const CONTROL_COLOR_TOKENS: ColorToken[] = [
  { key: "cardBackground", label: "Cards", hint: "Background of content cards.", default: "#FFFFFF" },
  { key: "sheetBackground", label: "Sheets", hint: "Bottom sheets and option panels.", default: "#FFFFFF" },
  { key: "modalBackground", label: "Modals", hint: "Dialog and modal surfaces.", default: "#FFFFFF" },
  { key: "headerBackground", label: "Header background", hint: "Top header on pushed pages and the main shell.", default: "#FFFFFF" },
  { key: "headerText", label: "Header title", hint: "Main header title text.", default: "#111714" },
  { key: "headerSubtext", label: "Header supporting text", hint: "Header subtitles and tagline.", default: "#4F5853" },
  { key: "headerIcon", label: "Header icons", hint: "Back and header action icons.", default: "#111714" },
  { key: "headerActionBackground", label: "Header action background", hint: "Round header action controls.", default: "#FAF8F4" },
  { key: "inputBackground", label: "Input background", hint: "Text fields at rest.", default: "#FAF8F4" },
  { key: "inputFocusedBackground", label: "Focused input background", hint: "Text fields while active.", default: "#FFFFFF" },
  { key: "inputText", label: "Input text", hint: "Entered form values.", default: "#111714" },
  { key: "inputPlaceholder", label: "Input placeholder", hint: "Placeholder and empty input text.", default: "#7A827E" },
  { key: "inputBorder", label: "Input border", hint: "Text field border at rest.", default: "#D8D1C4" },
  { key: "inputFocusedBorder", label: "Focused input border", hint: "Text field border while active.", default: "#032F22" },
  { key: "primaryButtonBackground", label: "Primary button background", hint: "Main calls to action.", default: "#032F22" },
  { key: "primaryButtonPressed", label: "Primary button pressed", hint: "Pressed state of main actions.", default: "#02271C" },
  { key: "primaryButtonText", label: "Primary button text", hint: "Label on main actions.", default: "#FFFFFF" },
  { key: "primaryButtonIcon", label: "Primary button icons", hint: "Icons inside main actions.", default: "#FFFFFF" },
  { key: "secondaryButtonBackground", label: "Secondary button background", hint: "Outlined and alternate actions.", default: "#FFFFFF" },
  { key: "secondaryButtonPressed", label: "Secondary button pressed", hint: "Pressed background of alternate actions.", default: "#EFF3EE" },
  { key: "secondaryButtonText", label: "Secondary button text", hint: "Label on alternate actions.", default: "#032F22" },
  { key: "secondaryButtonIcon", label: "Secondary button icons", hint: "Icons inside alternate actions.", default: "#032F22" },
  { key: "secondaryButtonBorder", label: "Secondary button border", hint: "Outline around alternate actions.", default: "#032F22" },
  { key: "goldButtonBackground", label: "Premium button background", hint: "Membership and premium actions.", default: "#E0C391" },
  { key: "goldButtonPressed", label: "Premium button pressed", hint: "Pressed premium action.", default: "#CFAE73" },
  { key: "goldButtonText", label: "Premium button text", hint: "Label and icon on premium actions.", default: "#032F22" },
  { key: "ghostButtonPressed", label: "Ghost button pressed", hint: "Pressed background for text-only actions.", default: "#EFF3EE" },
  { key: "ghostButtonText", label: "Ghost button text", hint: "Label and icon on text-only actions.", default: "#032F22" },
  { key: "inverseButtonBackground", label: "Inverse button background", hint: "Buttons shown on dark or image surfaces.", default: "#FFFFFF" },
  { key: "inverseButtonPressed", label: "Inverse button pressed", hint: "Pressed inverse action.", default: "#EFF3EE" },
  { key: "inverseButtonText", label: "Inverse button text", hint: "Label and icon on inverse actions.", default: "#032F22" },
  { key: "tabBackground", label: "Tab bar background", hint: "Bottom navigation bar.", default: "#032F22" },
  { key: "tabActiveBackground", label: "Active tab background", hint: "Raised active-tab disc.", default: "#FFFFFF" },
  { key: "tabActiveIcon", label: "Active tab icon", hint: "Selected bottom navigation icon.", default: "#032F22" },
  { key: "tabInactiveIcon", label: "Inactive tab icons", hint: "Unselected bottom navigation icons.", default: "rgba(255,255,255,0.72)" },
  { key: "tabActiveText", label: "Active tab text", hint: "Selected bottom navigation label.", default: "#FFFFFF" },
  { key: "tabInactiveText", label: "Inactive tab text", hint: "Unselected bottom navigation labels.", default: "rgba(255,255,255,0.72)" },
  { key: "iconPrimary", label: "Primary icons", hint: "Main action and feature icons.", default: "#032F22" },
  { key: "iconSecondary", label: "Secondary icons", hint: "Supporting icons.", default: "#4F5853" },
  { key: "iconMuted", label: "Muted icons", hint: "Inactive and metadata icons.", default: "#7A827E" },
  { key: "iconInverse", label: "Icons on dark backgrounds", hint: "Icons shown over primary fills or imagery.", default: "#FFFFFF" },
];

/** The rest of the palette — normally derived or rarely changed. */
export const ADVANCED_COLOR_TOKENS: ColorToken[] = [
  { key: "primaryDark", label: "Primary — pressed", hint: "Derived from primary unless set.", default: "#02271C" },
  { key: "secondary", label: "Secondary green", hint: "Derived from primary unless set.", default: "#0B4A37" },
  { key: "goldDark", label: "Accent — pressed", hint: "Derived from the accent unless set.", default: "#CFAE73" },
  { key: "ivory", label: "Ivory surface", hint: "Soft off-white panels.", default: "#FAF8F4" },
  { key: "cream", label: "Legacy cream surface", hint: "Older active compatibility surfaces.", default: "#F6F0E6" },
  { key: "overlay", label: "Brand image scrim", hint: "Standard dark green overlay on hero imagery.", default: "rgba(3,47,34,0.45)" },
  { key: "overlaySoft", label: "Soft brand overlay", hint: "Light green overlay on imagery and panels.", default: "rgba(3,47,34,0.18)" },
  { key: "primarySoft", label: "Sage divider", hint: "Dividers on a sage ground.", default: "#DDE5DC" },
  { key: "text.inverse", label: "Text on green", hint: "Text over primary fills and imagery.", default: "#FFFFFF" },
  { key: "text.brand", label: "Link text", hint: "Follows primary unless set.", default: "#032F22" },
  { key: "text.onGold", label: "Text on gold", hint: "Labels placed on premium gold surfaces.", default: "#032F22" },
  { key: "text.tertiary", label: "Tertiary text", hint: "Compatibility token for secondary metadata.", default: "#7A827E" },
  { key: "borderStrong", label: "Input borders", hint: "Inputs at rest.", default: "#D8D1C4" },
  { key: "borderFocus", label: "Legacy focused borders", hint: "Focused borders outside the shared input component.", default: "#032F22" },
  { key: "borderLight", label: "Light borders", hint: "Subtle separators and hairlines.", default: "#F1EEE7" },
  { key: "borderCream", label: "Cream borders", hint: "Compatibility border on older warm surfaces.", default: "#EEE6DA" },
  { key: "successSurface", label: "Success surface", hint: "Ground behind success banners.", default: "#E5F4EB" },
  { key: "warningSurface", label: "Warning surface", hint: "Ground behind warnings.", default: "#FFF3DD" },
  { key: "errorSurface", label: "Error surface", hint: "Ground behind errors.", default: "#FDE9E7" },
  { key: "info", label: "Info", hint: "Neutral informational states.", default: "#27678F" },
  { key: "infoSurface", label: "Info surface", hint: "Ground behind info banners.", default: "#E8F2F8" },
  { key: "disabled", label: "Disabled text", hint: "Inactive labels and icons.", default: "#8A918D" },
  { key: "disabledSurface", label: "Disabled surface", hint: "Inactive grounds.", default: "#F1F1EF" },
  { key: "disabledFill", label: "Disabled button fill", hint: "Disabled primary buttons.", default: "#D9DEDA" },
  { key: "primaryTint", label: "Primary tint", hint: "Selected icon and panel backgrounds.", default: "#EFF3EE" },
  { key: "surfaceMuted", label: "Muted surface", hint: "Subtle off-white backgrounds.", default: "#FAF8F4" },
  { key: "surfaceInverse", label: "Inverse surface", hint: "Large dark brand surfaces.", default: "#032F22" },
  { key: "lightGray", label: "Light neutral surface", hint: "Compatibility neutral panel background.", default: "#FAF8F4" },
  { key: "accent", label: "Soft accent", hint: "Small selected and highlighted areas.", default: "#EFF3EE" },
  { key: "surfaceAlt", label: "Alternate dark surface", hint: "Compatibility dark panels.", default: "#032F22" },
  { key: "surfaceAccent", label: "Accent surface", hint: "Compatibility sage panels.", default: "#EFF3EE" },
  { key: "forestGreen", label: "Legacy brand green", hint: "Compatibility token used by retained active components.", default: "#032F22" },
  { key: "white", label: "Pure white", hint: "Legacy white token still used by active specialist elements.", default: "#FFFFFF" },
  { key: "black", label: "Pure black", hint: "Legacy black token and media content.", default: "#000000" },
  { key: "shadow", label: "Neutral shadows", hint: "Form and modal shadows.", default: "#000000" },
  { key: "brandShadow", label: "Brand shadows", hint: "Standard card and navigation elevation.", default: "#032F22" },
  { key: "scrim", label: "Modal scrim", hint: "Backdrop behind regular modals.", default: "rgba(0,0,0,0.5)" },
  { key: "scrimStrong", label: "Strong modal scrim", hint: "Backdrop behind focused permission dialogs.", default: "rgba(0,0,0,0.6)" },
  { key: "mediaBackdrop", label: "Media backdrop", hint: "Full-screen photo and video background.", default: "rgba(0,0,0,0.94)" },
  { key: "mediaOverlay20", label: "Media overlay 20%", hint: "Light overlay on media controls.", default: "rgba(26,35,28,0.20)" },
  { key: "mediaOverlay25", label: "Media overlay 25%", hint: "Image carousel overlay.", default: "rgba(26,35,28,0.25)" },
  { key: "mediaOverlay60", label: "Media overlay 60%", hint: "Readable text overlay on reels.", default: "rgba(26,35,28,0.60)" },
  { key: "brandOverlay66", label: "Brand image overlay", hint: "Dark brand tint over treatment imagery.", default: "rgba(3,47,34,0.66)" },
  { key: "mediaOverlay02", label: "Media overlay 2%", hint: "Very light carousel image fade.", default: "rgba(3,47,34,0.02)" },
  { key: "mediaOverlay38", label: "Media overlay 38%", hint: "Carousel image readability fade.", default: "rgba(3,47,34,0.38)" },
  { key: "dividerTranslucent", label: "Translucent divider", hint: "Light separators over dropdown surfaces.", default: "rgba(0,0,0,0.08)" },
  { key: "mapPinShadow", label: "Map pin shadow", hint: "Shadow under the address map marker.", default: "rgba(3,47,34,0.40)" },
  { key: "authOverlay28", label: "Auth photo overlay 28%", hint: "Authentication photography gradient stop.", default: "rgba(44,62,47,0.28)" },
  { key: "authOverlay34", label: "Auth photo overlay 34%", hint: "Authentication photography gradient stop.", default: "rgba(44,62,47,0.34)" },
  { key: "authOverlay38", label: "Welcome photo overlay 38%", hint: "Welcome photography gradient stop.", default: "rgba(44,62,47,0.38)" },
  { key: "authOverlay70", label: "Auth photo overlay 70%", hint: "Authentication photography gradient stop.", default: "rgba(44,62,47,0.70)" },
  { key: "authOverlay72", label: "Welcome photo overlay 72%", hint: "Welcome photography gradient stop.", default: "rgba(44,62,47,0.72)" },
  { key: "authOverlay97", label: "Welcome photo overlay 97%", hint: "Welcome photography gradient stop.", default: "rgba(44,62,47,0.97)" },
  ...([12,14,15,16,18,20,22,30,32,55,65,70,72,75,78,85,90,92] as const).map((n) => ({
    key: `onPrimary${n}`, label: `White overlay ${n}%`, hint: "Text, borders and controls over primary or image surfaces.", default: `rgba(255,255,255,0.${n})`,
  })),
  { key: "socialAccent", label: "Social accent", hint: "Instagram/reels accent shadow.", default: "#D62976" },
  { key: "socialGold", label: "Social gradient gold", hint: "Instagram/reels gradient stop.", default: "#FEDA75" },
  { key: "socialOrange", label: "Social gradient orange", hint: "Instagram/reels gradient stop.", default: "#FA7E1E" },
  { key: "socialPurple", label: "Social gradient purple", hint: "Instagram/reels gradient stop.", default: "#962FBF" },
  { key: "socialBlue", label: "Social gradient blue", hint: "Instagram/reels gradient stop.", default: "#4F5BD5" },
];

export type FontSizeToken = { base: number; label: string; hint: string };
export const FONT_SIZE_TOKENS: FontSizeToken[] = [8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15, 15.5, 16, 17, 18, 19, 20, 21, 22, 24, 26, 28, 32, 34, 36]
  .map((base) => ({
    base,
    label: `${base}px base text`,
    hint: base <= 10 ? "Micro labels and counters" : base <= 12 ? "Captions and navigation" : base <= 14 ? "Body, labels and buttons" : base <= 17 ? "Lead text and item titles" : base <= 22 ? "Section and screen headings" : "Hero and empty-state display text",
  }));

export type CopyEntry = { key: string; label: string; default: string };
export type CopyGroup = { title: string; entries: CopyEntry[] };

export const COPY_GROUPS: CopyGroup[] = [
  { title: "Brand", entries: [
    { key: "brand.tagline.1", label: "tagline \u2014 1", default: "Skin." },
    { key: "brand.tagline.2", label: "tagline \u2014 2", default: "Aesthetics." },
    { key: "brand.tagline.3", label: "tagline \u2014 3", default: "Wellness." },
  ]},
  { title: "Welcome", entries: [
    { key: "welcome.title", label: "title", default: "Welcome to Zennara" },
    { key: "welcome.subtitle", label: "subtitle", default: "Login to access your account" },
    { key: "welcome.login", label: "login", default: "Login" },
    { key: "welcome.guest", label: "guest", default: "Continue As Guest" },
    { key: "welcome.registerPrompt", label: "registerPrompt", default: "New user? " },
    { key: "welcome.registerLink", label: "registerLink", default: "Register Here" },
  ]},
  { title: "Sign in", entries: [
    { key: "login.title", label: "title", default: "Sign in" },
    { key: "login.subtitle", label: "subtitle", default: "Enter your mobile number to continue" },
    { key: "login.cta", label: "cta", default: "Continue" },
  ]},
  { title: "OTP", entries: [
    { key: "otp.title", label: "title", default: "Enter the OTP" },
    { key: "otp.cta", label: "cta", default: "Verify & Continue" },
  ]},
  { title: "Sign up", entries: [
    { key: "signup.step1.title", label: "step1 \u2014 title", default: "Register with your number" },
    { key: "signup.step1.subtitle", label: "step1 \u2014 subtitle", default: "We'll send an OTP on WhatsApp to verify it's you" },
    { key: "signup.step3.title", label: "step3 \u2014 title", default: "A few details about you" },
    { key: "signup.step3.subtitle", label: "step3 \u2014 subtitle", default: "This is all we need to set up your profile" },
    { key: "signup.cta", label: "cta", default: "Create Account" },
  ]},
  { title: "Tabs", entries: [
    { key: "tabs.home", label: "home", default: "Home" },
    { key: "tabs.consultation", label: "consultation", default: "Consultation" },
    { key: "tabs.treatments", label: "treatments", default: "Treatment" },
    { key: "tabs.appointments", label: "appointments", default: "Appointment" },
    { key: "tabs.profile", label: "profile", default: "Profile" },
  ]},
  { title: "Home", entries: [
    { key: "home.greeting.morning", label: "greeting \u2014 morning", default: "Good morning" },
    { key: "home.greeting.afternoon", label: "greeting \u2014 afternoon", default: "Good afternoon" },
    { key: "home.greeting.evening", label: "greeting \u2014 evening", default: "Good evening" },
    { key: "home.book.cta", label: "book \u2014 cta", default: "Book an appointment" },
    { key: "home.prompt.title", label: "prompt \u2014 title", default: "Book your appointment" },
    { key: "home.prompt.subtitle", label: "prompt \u2014 subtitle", default: "Take the first step towards healthy skin & hair" },
    { key: "home.prompt.cta", label: "prompt \u2014 cta", default: "Book now" },
    { key: "home.products.heading", label: "products \u2014 heading", default: "Products" },
    { key: "home.products.subheading", label: "products \u2014 subheading", default: "Get delivered to your doorstep" },
    { key: "home.products.viewAll", label: "products \u2014 viewAll", default: "View all" },
    { key: "home.reviews.heading", label: "reviews \u2014 heading", default: "Celebrity love for Zennara" },
    { key: "home.reviews.subheading", label: "reviews \u2014 subheading", default: "Stories from faces you know" },
    { key: "home.reels.ctaTitle", label: "reels \u2014 ctaTitle", default: "Follow us on Instagram" },
    { key: "home.reels.ctaSubtitle", label: "reels \u2014 ctaSubtitle", default: "Daily skin tips, before & after results, expert advice & exclusive offers" },
  ]},
  { title: "Consultation flow", entries: [
    { key: "consult.doctors.title", label: "doctors \u2014 title", default: "Select dermatologist" },
    { key: "consult.doctors.bookingAt", label: "doctors \u2014 bookingAt", default: "Booking at" },
    { key: "consult.doctors.available", label: "doctors \u2014 available", default: "Available dermatologists" },
    { key: "consult.doctors.changeClinic", label: "doctors \u2014 changeClinic", default: "Change clinic" },
    { key: "consult.doctors.chooseClinic", label: "doctors \u2014 chooseClinic", default: "Choose clinic" },
    { key: "consult.doctors.proceed", label: "doctors \u2014 proceed", default: "Proceed" },
    { key: "consult.doctors.any", label: "doctors \u2014 any", default: "Any available dermatologist" },
    { key: "consult.datetime.selectDate", label: "datetime \u2014 selectDate", default: "Select a date" },
    { key: "consult.datetime.selectedDate", label: "datetime \u2014 selectedDate", default: "Selected date" },
    { key: "consult.datetime.availableTimes", label: "datetime \u2014 availableTimes", default: "Available times" },
    { key: "consult.datetime.booked", label: "datetime \u2014 booked", default: "Booked" },
    { key: "consult.select.title", label: "select \u2014 title", default: "Choose a specialist" },
    { key: "consult.review.title", label: "review \u2014 title", default: "Review & Confirm" },
    { key: "consult.review.summary", label: "review \u2014 summary", default: "Booking summary" },
    { key: "consult.review.payment", label: "review \u2014 payment", default: "Payment summary" },
    { key: "consult.review.fee", label: "review \u2014 fee", default: "Consultation fee" },
    { key: "consult.review.total", label: "review \u2014 total", default: "Total payable" },
    { key: "consult.done.title", label: "done \u2014 title", default: "Consultation confirmed" },
    { key: "consult.done.cta", label: "done \u2014 cta", default: "Back to home" },
  ]},
  { title: "Appointments", entries: [
    { key: "appointments.empty.upcoming", label: "empty \u2014 upcoming", default: "Nothing booked yet" },
    { key: "appointments.empty.completed", label: "empty \u2014 completed", default: "No completed visits yet" },
    { key: "appointments.empty.cancelled", label: "empty \u2014 cancelled", default: "No cancelled appointments" },
    { key: "appointments.empty.noshow", label: "empty \u2014 noshow", default: "No missed appointments" },
    { key: "appointments.cta.consultation", label: "cta \u2014 consultation", default: "Book a consultation" },
    { key: "appointments.cta.treatments", label: "cta \u2014 treatments", default: "Browse treatments" },
    { key: "appointments.signin.title", label: "signin \u2014 title", default: "Sign in to see your appointments" },
    { key: "appointments.signin.subtitle", label: "signin \u2014 subtitle", default: "Bookings belong to your account, so we need to know who you are." },
  ]},
  { title: "Appointment detail", entries: [
    { key: "appointment.share", label: "share", default: "Share appointment slip" },
    { key: "appointment.reschedule", label: "reschedule", default: "Reschedule" },
    { key: "appointment.review.ask", label: "review \u2014 ask", default: "How was your visit?" },
    { key: "appointment.review.thanks", label: "review \u2014 thanks", default: "Thanks for your review" },
    { key: "appointment.review.done", label: "review \u2014 done", default: "You've already reviewed this visit" },
    { key: "appointment.review.submit", label: "review \u2014 submit", default: "Submit review" },
  ]},
  { title: "Reschedule", entries: [
    { key: "reschedule.preferredTimes", label: "preferredTimes", default: "Preferred new times" },
    { key: "reschedule.cta", label: "cta", default: "Request reschedule" },
  ]},
  { title: "Shop", entries: [
    { key: "shop.title", label: "title", default: "Our Products" },
    { key: "shop.subtitle", label: "subtitle", default: "Trusted skincare for healthy, glowing you." },
    { key: "shop.search", label: "search", default: "Search products" },
    { key: "shop.empty.title", label: "empty \u2014 title", default: "No products found" },
    { key: "shop.empty.filters", label: "empty \u2014 filters", default: "Try adjusting your filters." },
    { key: "shop.empty.soon", label: "empty \u2014 soon", default: "Products will appear here soon." },
  ]},
  { title: "Treatments tab", entries: [
    { key: "treatments.tiers.heading", label: "tiers \u2014 heading", default: "Who would you like to see?" },
    { key: "treatments.search", label: "search", default: "Search treatments" },
    { key: "treatments.card.cta", label: "card \u2014 cta", default: "Book Consultation" },
  ]},
  { title: "Treatment detail", entries: [
    { key: "treatment.section.about", label: "section \u2014 about", default: "About this treatment" },
    { key: "treatment.section.benefits", label: "section \u2014 benefits", default: "Key benefits" },
    { key: "treatment.section.idealFor", label: "section \u2014 idealFor", default: "Ideal for" },
    { key: "treatment.section.preCare", label: "section \u2014 preCare", default: "Before your visit" },
    { key: "treatment.section.postCare", label: "section \u2014 postCare", default: "After your treatment" },
    { key: "treatment.section.faqs", label: "section \u2014 faqs", default: "Questions" },
    { key: "treatment.section.reviews", label: "section \u2014 reviews", default: "Client reviews" },
  ]},
  { title: "Cart", entries: [
    { key: "cart.empty.title", label: "empty \u2014 title", default: "Your cart is empty" },
    { key: "cart.empty.subtitle", label: "empty \u2014 subtitle", default: "Add products to get started." },
    { key: "cart.empty.cta", label: "empty \u2014 cta", default: "Continue shopping" },
    { key: "cart.coupons.title", label: "coupons \u2014 title", default: "Coupons & offers" },
    { key: "cart.bill.title", label: "bill \u2014 title", default: "Bill summary" },
    { key: "cart.bill.subtotal", label: "bill \u2014 subtotal", default: "Subtotal" },
    { key: "cart.bill.delivery", label: "bill \u2014 delivery", default: "Delivery" },
    { key: "cart.checkout.cta", label: "checkout \u2014 cta", default: "Proceed to checkout" },
  ]},
  { title: "Checkout", entries: [
    { key: "checkout.address.title", label: "address \u2014 title", default: "DELIVERY ADDRESS" },
    { key: "checkout.summary.title", label: "summary \u2014 title", default: "ORDER SUMMARY" },
    { key: "checkout.payment.title", label: "payment \u2014 title", default: "PAYMENT METHOD" },
    { key: "checkout.online.subtitle", label: "online \u2014 subtitle", default: "UPI, Cards, NetBanking & More" },
    { key: "checkout.cod.title", label: "cod \u2014 title", default: "Cash on Delivery" },
    { key: "checkout.cod.subtitle", label: "cod \u2014 subtitle", default: "Pay when you receive" },
    { key: "checkout.place.cta", label: "place \u2014 cta", default: "Place Order" },
  ]},
  { title: "Search", entries: [
    { key: "search.popular", label: "popular", default: "Popular searches" },
    { key: "search.recommended", label: "recommended", default: "Recommended for you" },
  ]},
  { title: "Notifications", entries: [
    { key: "notifications.markAllRead", label: "markAllRead", default: "Mark all read" },
  ]},
  { title: "Chat", entries: [
    { key: "chat.status.online", label: "status \u2014 online", default: "Reception usually replies within minutes" },
    { key: "chat.restart", label: "restart", default: "Start a new conversation" },
  ]},
  { title: "Profile", entries: [
    { key: "profile.section.account", label: "section \u2014 account", default: "Account" },
    { key: "profile.section.support", label: "section \u2014 support", default: "Support & Settings" },
    { key: "profile.row.personal", label: "row \u2014 personal", default: "Personal Information" },
    { key: "profile.row.allergies", label: "row \u2014 allergies", default: "Allergies" },
    { key: "profile.row.membership", label: "row \u2014 membership", default: "Zen Membership" },
    { key: "profile.row.help", label: "row \u2014 help", default: "Help & Support" },
    { key: "profile.member.promoTitle", label: "member \u2014 promoTitle", default: "Become a Zen Member" },
    { key: "profile.member.promoSubtitle", label: "member \u2014 promoSubtitle", default: "A year of signature treatments, 10% off & member perks" },
    { key: "profile.signout", label: "signout", default: "Sign out" },
  ]},
  { title: "Personal info", entries: [
    { key: "personal.title", label: "title", default: "Personal Information" },
    { key: "personal.save", label: "save", default: "Save changes" },
  ]},
  { title: "Addresses", entries: [
    { key: "addresses.title", label: "title", default: "Saved Addresses" },
    { key: "addresses.add", label: "add", default: "Add a new address" },
    { key: "addresses.empty", label: "empty", default: "No saved addresses" },
  ]},
  { title: "Orders", entries: [
    { key: "orders.title", label: "title", default: "Orders" },
    { key: "orders.browse", label: "browse", default: "Browse products" },
  ]},
  { title: "Packages", entries: [
    { key: "packages.title", label: "title", default: "My Packages" },
  ]},
  { title: "Clinic history", entries: [
    { key: "clinicHistory.title", label: "title", default: "Clinic History" },
  ]},
  { title: "Account settings", entries: [
    { key: "settings.title", label: "title", default: "Account Settings" },
    { key: "settings.export", label: "export", default: "Export my data" },
    { key: "settings.delete", label: "delete", default: "Delete my account" },
  ]},
  { title: "Membership", entries: [
    { key: "membership.title", label: "title", default: "Zen Membership" },
    { key: "membership.pitch", label: "pitch", default: "A year of Zennara's signature treatments and privileges." },
    { key: "membership.cta", label: "cta", default: "Become a Zen Member" },
  ]},
  { title: "Booking", entries: [
    { key: "booking.confirm.cta", label: "confirm \u2014 cta", default: "Confirm booking" },
    { key: "booking.visitCode.hint", label: "visitCode \u2014 hint", default: "Show this code at reception to check in." },
  ]},
  { title: "Guest prompt", entries: [
    { key: "guest.title", label: "title", default: "Sign In Required" },
    { key: "guest.message", label: "message", default: "Please sign in to access this feature" },
    { key: "guest.signIn", label: "signIn", default: "Sign In" },
    { key: "guest.createAccount", label: "createAccount", default: "Create Account" },
    { key: "guest.continue", label: "continue", default: "Continue Browsing" },
  ]},
  { title: "Help & support", entries: [
    { key: "help.title", label: "title", default: "Help & Support" },
    { key: "help.faq.heading", label: "faq \u2014 heading", default: "Common questions" },
    { key: "help.message.heading", label: "message \u2014 heading", default: "Send us a message" },
    { key: "help.clinics.heading", label: "clinics \u2014 heading", default: "Our clinics" },
  ]},
  { title: "Common", entries: [
    { key: "common.save", label: "save", default: "Save" },
    { key: "common.cancel", label: "cancel", default: "Cancel" },
  ]},
];
